# **Numpy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

Element wise operations

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

c = a + b

print(c)

[[10 10 10]

 [10 10 10]

 [10 10 10]]


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

c = a + b

ValueError: ignored

In [ ]:
line = a.reshape((9))
line

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
line = line.reshape((3, 3))
line

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Element wise functions

In [ ]:
angles = np.array([3.14, 3.14/2, 6.28])

cosine_of_angles = np.cos(angles)

print('Cosine of the given array of angles = ', cosine_of_angles)

Cosine of the given array of angles =  [-9.99998732e-01  7.96326711e-04  9.99994927e-01]


Transpose

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Indexing and selection

In [ ]:
arandomarray = np.array([1, 6, 5, 9, 10, 74, 24, 5])

print(arandomarray[arandomarray%2 == 1])

print(arandomarray[arandomarray%2 == 0])

[1 5 9 5]

[ 6 10 74 24]


In [ ]:
arandomarray[:3]

array([1, 6, 5])

In [ ]:
arandomarray[3:]

array([ 9, 10, 74, 24,  5])

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a[:][:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[:][0]

array([1, 2, 3])

In [ ]:
a.T[:][0]

array([1, 4, 7])

# **Pandas**

In [ ]:
import pandas as pd

In [ ]:
arr1 = [1, 2, 3]
arr2 = {'a':1, 'b':2, 'c':3}

In [ ]:
labels = ['a','b','c']
mydata = [1,2,3]

pd.Series(mydata, labels)

a    1
b    2
c    3
dtype: int64

In [ ]:
print("\n","\b")
ser1 = pd.Series([1,2,3,4], index=['USA','UK','China','Russia'])
print(ser1,"\n")
print(type(ser1))





USA       1

UK        2

China     3

Russia    4

dtype: int64 



<class 'pandas.core.series.Series'>


In [ ]:
ser1 = pd.Series([1,2,5,4],index = ['USA','UK','China','Russia'],dtype=float)
print("Data 1:\n", ser1)
print('\n')

ser2 = pd.Series([6,2,1,5],index = ['UK','China','USA','Russia'],dtype=float)
print("Data 2:\n", ser2)

Data 1:

 USA       1.0

UK        2.0

China     5.0

Russia    4.0

dtype: float64





Data 2:

 UK        6.0

China     2.0

USA       1.0

Russia    5.0

dtype: float64


In [ ]:
print(ser1 + ser2)

China     7.0

Russia    9.0

UK        8.0

USA       2.0

dtype: float64


In [ ]:
print((ser1+ser2)['USA'])

2.0


In [ ]:
print((ser1*2))

USA        2.0

UK         4.0

China     10.0

Russia     8.0

dtype: float64


In [ ]:
print((ser1**2))

USA        1.0

UK         4.0

China     25.0

Russia    16.0

dtype: float64


In [ ]:
print((ser1**0.5))

USA       1.000000

UK        1.414214

China     2.236068

Russia    2.000000

dtype: float64


In [ ]:
r1 = [1, 5, 3, 6, 10]
r1 = pd.Series(r1)

r2 = [60, 10, 50, 70, 36]
r2 = pd.Series(r2)

pd.concat([r1, r2])

In [ ]:
pd.concat([r2, r1])

# Libraries: Random numbers.

In [ ]:
import random

print(random.random())

0.81332125135732


In [ ]:
List = []

for i in range(10):
  List.append(random.random())

print(List)

[0.613326820546709, 0.0442606328646209, 0.004055144158407464, 0.13397252704913387, 0.941002271395834, 0.3028605620290723, 0.3661456016604264, 0.8981962445391883, 0.31436380495645067, 0.5489821840124055]


In [ ]:
r = np.array([[10, 100], [49, 25]])
for i in range(2):
  for j in range(2):
    if r[i][j] > 50:
      r[i][j] = 1
    else:
      r[i][j] = 0
r

array([[0, 1],
       [0, 0]])